name: Build and Deploy packages to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: us-central1
  REPO_NAME: symphonize
  BUCKET_NAME: bucketcloudr

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Enable necessary components
        run: gcloud components install beta

      - name: Build and push Docker image to GCR
        run: |
          docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud beta run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --port 8000 \
          --timeout 900s \
          --platform "managed" \
          --allow-unauthenticated \
          --execution-environment gen2 \
          --add-volume name=gcs-volume,type=gcs,volume-source=gcs-bucket=$BUCKET_NAME \
          --add-volume-mount name=gcs-volume,mount-path=/mnt/data

      - name: Upload build logs to Cloud Storage
        run: |
          echo "Build logs for $REPO_NAME" > build_logs.txt
          gsutil cp build_logs.txt gs://$BUCKET_NAME/build_logs/$GITHUB_SHA-log.txt
